# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

registries:
  pypi-standard:
    type: python-index
    url: "https://pypi.org/simple"

updates:
  # seemingly something with the pyproject is broken, as it doesn't work with pip or uv as eco system
  - package-ecosystem: "uv"
    directory: "backend/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: detoxify
      - dependency-name: torch
    registries: [ "pypi-standard" ]
    groups:
      dependencies:
        patterns:
          - "*" # Group all dependencies
      
  - package-ecosystem: "npm"
    directory: "frontend/"
    schedule:
      interval: "daily"
    groups:
      dependencies:
        patterns:
          - "*" # Group all dependencies
    commit-message:
      prefix: "#patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*" # Group all dependencies
    commit-message:
      prefix: "#patch"
