services:
  custos:
    image: glitchdevx/custos:latest
    restart: always
    ports:
      - "5365:5365/tcp"
  custos-ui:
    image: glitchdevx/custos-ui:latest
    restart: always
    depends_on:
      - custos
    ports:
      - "3000:80/tcp"
