services:
  custos:
    image: glitchdevx/custos:latest
    restart: always
    ports:
      - "5365:5365/tcp"
    depends_on:
      - db
    environment:
      DATABASE_URI: 'mysql+pymysql://user:password@db:5385/custos'
  custos-ui:
    image: glitchdevx/custos-ui:latest
    restart: always
    depends_on:
      - custos
    ports:
      - "3000:80/tcp"
