services:
  custos:
    image: custos:latest
    restart: always
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://user:password@db/custos'
  custos-ui:
    image: custos-ui:latest
    restart: always
    depends_on:
      - custos
    ports:
      - 3070:80
    expose:
      - 3070
  ollama:
    image: ollama/ollama:latest
    entrypoint:
      [
        "/bin/bash",
        "-c",
        "ollama serve & sleep 5 && ollama pull gemma3:4b && wait",
      ]
    expose:
      - 11434/tcp
    ports:
      - "11434:11434/tcp"
    healthcheck:
      test: ollama --version || exit 1
    volumes:
      - ollama:/root/.ollama
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'custos'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
  ollama: