services:
  custos:
    image: glitchdevx/custos:latest
    restart: always
    ports:
      - "5365:5365/tcp"
    depends_on:
      - db
      - ollama
    environment:
      DATABASE_URI: 'mysql+pymysql://user:password@db/custos'
  custos-ui:
    image: glitchdevx/custos-ui:latest
    restart: always
    depends_on:
      - custos
    ports:
      - "3000:80/tcp"
  ollama:
    image: ollama/ollama:latest
    restart: always
    entrypoint:
      [ "/bin/bash", "-c", "ollama serve & sleep 5 && ollama pull gemma3:4b && wait" ]
    ports: # required for dev
      - "5375:11434/tcp"
    expose:
      - "5375:11434/tcp"
    healthcheck:
      test: ollama --version || exit 1
    volumes:
      - ollama:/root/.ollama
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'custos'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports: # required for dev
      - '5385:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
  ollama: