[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cryptography>=44.0.2",
    "detoxify>=0.5.2",
    "dnspython>=2.7.0",
    "flask>=3.1.0",
    "flask-cors>=5.0.1",
    "flask-limiter>=4.1.1",
    "flask-restx>=1.3.0",
    "prometheus-client>=0.22.1",
    "prometheus-flask-exporter>=0.23.2",
    "requests>=2.28.1",
    "torch>=2.8.0",
    "waitress>=3.0.2",
    "watchdog>=6.0.0",
]

[tool.uv.sources]
torch = { index = "pytorch_cpu" }

[[tool.uv.index]]
name = "pytorch_cpu"
url = "https://download.pytorch.org/whl/cpu"


[project.optional-dependencies]
dev = [
    "coverage>=7.8.0",
    "pytest>=8.3.5",
]

[tool.coverage.run]
omit = [
    # omit pytorch-generated files in /tmp
    "/tmp/*",
]

[tool.pyrefly]
project-includes = ["app/**"]
project-excludes = [
    "**/__pycache__",
    "**/*venv/**/*",
]
