name: Build and Release

permissions: write-all

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  get-version-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.new_tag }}
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          PRERELEASE: true
      
      - name: Echo Tag to output
        run: |
          echo ${{ steps.tag.outputs.new_tag }}

  build-backend:
    runs-on: ubuntu-latest
    needs: get-version-tag
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Build and push
        uses: docker/bake-action@v6
        env:
          CUSTOS_TAG: ${{ needs.get-version-tag.outputs.tag }}
        with:
          workdir: ../
          targets: backend
          push: true
          pull: true
        
  build-frontend:
    runs-on: ubuntu-latest
    needs: get-version-tag
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  
      
      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      
      - name: Cache npm Dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            frontend/node_modules
            frontend/.nuxt
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build Frontend
        run: npm run generate

      - name: Build and push
        uses: docker/bake-action@v6
        env:
          CUSTOS_TAG: ${{ needs.get-version-tag.outputs.tag }}
        with:
          workdir: ../
          targets: frontend
          push: true
          pull: true

  release:
    runs-on: ubuntu-latest
    needs: [get-version-tag, build-backend, build-frontend]
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Download Backend Docker image tar
        uses: actions/download-artifact@v4
        with:
          name: custos-image
          path: .

      - name: Download Frontend Docker image tar
        uses: actions/download-artifact@v4
        with:
          name: custos-ui-image
          path: .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.get-version-tag.outputs.tag }}
          append_body: hub.docker.com/glitchdevx/custos
          files: |
            custos-latest.tar
            custos-ui-latest.tar
