name: Build and Release

permissions: write-all

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  get-version-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.new_tag }}
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          PRERELEASE: true
      
      - name: Echo Tag to output
        run: |
          echo ${{ steps.tag.outputs.new_tag }}

  build-backend:
    runs-on: ubuntu-latest
    needs: get-version-tag
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  

      - name: Build and push
        uses: docker/bake-action@v6
        env:
          CUSTOS_TAG: ${{ needs.get-version-tag.outputs.tag }}
        with:
          targets: backend
          push: true
          pull: true
        
  build-frontend:
    runs-on: ubuntu-latest
    needs: get-version-tag
    steps:
      - name: Get latest code
        uses: actions/checkout@v4
      
      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      
      - name: Cache npm Dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            frontend/node_modules
            frontend/.nuxt
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd frontend
          npm ci

      - name: Build Frontend
        run: |
          cd frontend
          npm run generate
          ls -a

      - name: List dirs (Debugging)
        run: |
          cd frontend
          ls -a

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/bake-action@v6
        env:
          CUSTOS_TAG: ${{ needs.get-version-tag.outputs.tag }}
        with:
          targets: frontend
          push: true
          pull: false
          no-cache: 'true'

  release:
    runs-on: ubuntu-latest
    needs: [get-version-tag, build-backend, build-frontend]
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.get-version-tag.outputs.tag }}
          append_body: |
            ## Images

            ### [Backend](https://hub.docker.com/repository/docker/glitchdevx/custos/general)
            ```bash
            docker pull glitchdevx/custos
            ```
                    
            ### [Frontend](https://hub.docker.com/repository/docker/glitchdevx/custos-ui/general)
            ```bash
            docker pull glitchdevx/custos-ui
            ```
