name: Build and Release

permissions: write-all

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  get-version-tag:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.new_tag }}
      was-updated: ${{ steps.tag.outputs.old_tag != steps.tag.outputs.new_tag }}
    steps:
      - name: Get latest code
        uses: actions/checkout@v5

      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          PRERELEASE: true
      
      - name: Echo Tag to output
        run: |
          echo "New Tag: ${{ steps.tag.outputs.new_tag }}"
          echo "Was Updated: ${{ steps.tag.outputs.old_tag != steps.tag.outputs.new_tag }}"

  test-backend:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Get latest code
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install

      - name: Setup venv
        run: uv venv

      - name: Install dependencies
        run: uv pip install -r pyproject.toml --extra dev

      - name: Run tests
        run: |
          uv run coverage run -m pytest
          echo '### Coverage Summary' >> $GITHUB_STEP_SUMMARY
          uv run coverage report --format=markdown >> $GITHUB_STEP_SUMMARY

  build-backend:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    needs: [get-version-tag, test-backend]
    steps:
      - name: Get latest code
        uses: actions/checkout@v5

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/bake-action@v6
        env:
          CUSTOS_TAG: ${{ needs.get-version-tag.outputs.tag }}
        with:
          targets: backend
          push: ${{ needs.get-version-tag.outputs.was-updated }}
          pull: true
        
  build-frontend:
    runs-on: ubuntu-latest
    needs: get-version-tag
    timeout-minutes: 20
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Get latest code
        uses: actions/checkout@v5
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm"
          cache-dependency-path: frontend/pnpm-lock.yaml
      
      - name: Install dependencies
        run: pnpm i

      - name: Lint Code
        run: pnpm lint

      - name: Run Typecheck
        run: pnpm typecheck

      - name: Build Frontend
        run: pnpm generate

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/bake-action@v6
        env:
          CUSTOS_TAG: ${{ needs.get-version-tag.outputs.tag }}
        with:
          source: .
          targets: frontend
          push: ${{ needs.get-version-tag.outputs.was-updated }}
          pull: true

  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [get-version-tag, build-backend, build-frontend]
    if: ${{ needs.get-version-tag.outputs.was-updated == 'true' }}
    steps:
      - name: Get latest code
        uses: actions/checkout@v5

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.get-version-tag.outputs.tag }}
          body: |
            ## Images on Dockerhub

            ### [Backend](https://hub.docker.com/repository/docker/glitchdevx/custos/general)
            ```bash
            docker pull glitchdevx/custos:${{ needs.get-version-tag.outputs.tag }}
            ```

            ### [Frontend](https://hub.docker.com/repository/docker/glitchdevx/custos-ui/general)
            ```bash
            docker pull glitchdevx/custos-ui:${{ needs.get-version-tag.outputs.tag }}
            ```
