name: Build and Release

permissions: write-all

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  get-version-tag:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.new_tag }}
      was-updated: ${{ steps.tag.outputs.old_tag == '' }}
    steps:
      - name: Get latest code
        uses: actions/checkout@v5

      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          PRERELEASE: true
      
      - name: Echo Tag to output
        run: |
          echo ${{ steps.tag.outputs.new_tag }}
          echo ${{ steps.tag.outputs.part }}
          echo ${{ steps.tag.outputs.tag }}
          echo ${{ steps.tag.outputs.old_tag }}
          echo ${{ steps.tag.outputs.old_tag == '' }}

  test-backend:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Get latest code
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install

      - name: Setup venv
        run: uv venv

      - name: Install dependencies
        run: uv pip install -r pyproject.toml --extra dev

      - name: Run tests
        run: |
          uv run coverage run -m pytest
          echo '### Coverage Summary' >> $GITHUB_STEP_SUMMARY
          uv run coverage report --format=markdown >> $GITHUB_STEP_SUMMARY

  build-backend:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    needs: [get-version-tag, test-backend]
    steps:
      - name: Get latest code
        uses: actions/checkout@v5

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/bake-action@v6
        env:
          CUSTOS_TAG: ${{ needs.get-version-tag.outputs.tag }}
        with:
          targets: backend
          push: true
          pull: true
        
  build-frontend:
    runs-on: ubuntu-latest
    needs: get-version-tag
    timeout-minutes: 20
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Get latest code
        uses: actions/checkout@v5
      
      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      
      - name: Cache npm Dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            .nuxt
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Lint Code
        run: npm run lint

      - name: Run Typecheck
        run: npx nuxt typecheck

      - name: Build Frontend
        run: npm run generate

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # We can't use the docker/bake-action as it is git context based
      # it could be used when the full build is possible in the dockerfile
      - name: Build and push
        env:
          CUSTOS_TAG: ${{ needs.get-version-tag.outputs.tag }}
        run: |
          cd ..
          docker buildx bake frontend --push

  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [get-version-tag, build-backend, build-frontend]
    if: ${{ needs.get-version-tag.outputs.was-updated }}
    steps:
      - name: Get latest code
        uses: actions/checkout@v5

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.get-version-tag.outputs.tag }}
          append_body: true
          body: |
            ## Images on Dockerhub

            ### [Backend](https://hub.docker.com/repository/docker/glitchdevx/custos/general)
            ```bash
            docker pull glitchdevx/custos:${{ needs.get-version-tag.outputs.tag }}
            ```

            ### [Frontend](https://hub.docker.com/repository/docker/glitchdevx/custos-ui/general)
            ```bash
            docker pull glitchdevx/custos-ui:${{ needs.get-version-tag.outputs.tag }}
            ```
