name: Build and Release

permissions: write-all

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  get-version-tag:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          PRERELEASE: true
      
      - name: Echo Tag to output
        run: |
          echo ${{ steps.tag.outputs.new_tag }}
          echo "tag=${{ steps.tag.outputs.new_tag }}" >> "$GITHUB_OUTPUT"

  build-backend:
    runs-on: [self-hosted, linux, x64]
    needs: get-version-tag
    steps:
      - name: Get latest code
        uses: actions/checkout@v4
      
      - name: Build Docker image
        run: |
          docker build -t custos:${{needs.get-version-tag.outputs.tag}} -t custos:latest .

      - name: Save Docker image to a tar file
        run: |
          docker save custos:latest -o custos-latest.tar

      - name: Upload Docker image tar as artifact
        uses: actions/upload-artifact@v4
        with:
          name: custos-latest
          path: custos-latest.tar
  
  build-frontend:
    runs-on: [self-hosted, linux, x64]
    needs: get-version-tag
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Get latest code
        uses: actions/checkout@v4
      
      - name: Build Frontend
        run: npm run generate

      - name: Build Docker image
        run: docker build -t custos-ui:${{needs.get-version-tag.outputs.tag}} -t custos-ui:latest .

      - name: Save Docker image to a tar file
        run: |
          docker save custos-ui:latest -o custos-ui-latest.tar

      - name: Upload Docker image tar as artifact
        uses: actions/upload-artifact@v4
        with:
          name: custos-ui-image
          path: custos-ui-latest.tar

  release:
    runs-on: [self-hosted, linux, x64]
    needs: [build-backend, build-frontend]
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          PRERELEASE: true

      - name: Download Backend Docker image tar
        uses: actions/download-artifact@v4
        with:
          name: custos-image
          path: .

      - name: Download Frontend Docker image tar
        uses: actions/download-artifact@v4
        with:
          name: custos-ui-image
          path: .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:

          tag_name: ${{ steps.tag.outputs.new_tag }}
          files: |
            custos-latest.tar
            custos-ui-latest.tar
