name: Ping Runner

on:
  workflow_dispatch:

jobs:
  manual-job:
    runs-on: [self-hosted, linux, x64]
    timeout-minutes: 1
    steps:
      - name: Check runner health
        run: |
          echo "Checking runner health..."
          if [ -z "$(pgrep -f actions-runner)" ]; then
            echo "Runner is not available! Exiting..."
            exit 1
          fi
