name: PR Checks
on:
  workflow_dispatch:
  pull_request: 
    branches: [main]
    paths-ignore:
      - 'README.md'
      - '.gitignore'

jobs:
  frontend:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      
      - name: Cache npm Dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            frontend/node_modules
            frontend/.nuxt
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm ci
        
      - name: Lint Code
        run: npm run lint

      - name: Run Typecheck
        run: npx nuxt typecheck

      # possibly execute test later on

  backend-linting:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Linting Backend code
        uses: astral-sh/ruff-action@v3
        with:
          args: check --select B
          src: "./backend"
          
  backend-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults:
      run:
        working-directory: backend
    needs: backend-linting
    steps:
      - name: Get latest code
        uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Setup venv
        run: uv venv

      - name: Install dependencies
        run: uv pip install -r pyproject.toml --extra dev

      - name: Run tests
        run: |
          uv run coverage run -m pytest
          echo '### Coverage Summary' >> $GITHUB_STEP_SUMMARY
          uv run coverage report --format=markdown >> $GITHUB_STEP_SUMMARY
