name: PR Checks
on:
  workflow_dispatch:
  pull_request: 
    branches: [main]
    paths-ignore:
      - 'README.md'
      - '.gitignore'

jobs:
  frontend:
    runs-on: [self-hosted, linux, x64]
    timeout-minutes: 10
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      
      - name: Cache npm Dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            frontend/node_modules
            frontend/.nuxt
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm ci
        
      - name: Lint Code
        run: npm run lint

      # possibly execute test later on

  linting:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Linting Backend code
        uses: astral-sh/ruff-action@v3
        with:
          args: check --select B
          src: "./backend"
          
  backend:
    runs-on: [self-hosted, linux, x64]
    timeout-minutes: 30
    defaults:
      run:
        working-directory: backend
    needs: linting
    steps:
      - name: Get latest code
        uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install
      
      - name: Install requirements
        run: uv sync

      - name: Run tests
        run: uv run pytest